name: Deployment

on:
  pull_request:
    types:
      - closed

jobs:
  upgrade:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ["PMVG Homolog"]
    environment:
      name: ${{ matrix.environment }}

    steps:
      - name: Echo environment
        run: |
          echo "Current environment: ${{ matrix.environment }}}"

      - name: Setup SSH Keys
        run: |
          mkdir -p ~/.ssh
          
          # Setup Target Server SSH key
          echo "${{ secrets.TARGET_SSH_PRIVATE_KEY }}" > ~/.ssh/target_key
          echo "" >> ~/.ssh/target_key
          chmod 600 ~/.ssh/target_key
          
          # Create SSH config file
          cat > ~/.ssh/config << EOF
          Host target
            HostName ${{ vars.TARGET_HOST }}
            User ${{ vars.TARGET_USER }}
            IdentityFile ~/.ssh/target_key
            StrictHostKeyChecking no
          EOF
          
          # If bridge host is configured, add bridge configuration
          if [ ! -z "${{ vars.BRIDGE_HOST }}" ]; then
            echo "${{ secrets.BRIDGE_SSH_PRIVATE_KEY }}" > ~/.ssh/bridge_key
            echo "" >> ~/.ssh/bridge_key
            chmod 600 ~/.ssh/bridge_key
            
            # Add bridge configuration
            cat >> ~/.ssh/config << EOF
          
          Host bridge
            HostName ${{ vars.BRIDGE_HOST }}
            User ${{ vars.BRIDGE_USER }}
            IdentityFile ~/.ssh/bridge_key
            StrictHostKeyChecking no
          EOF
          fi
          
          chmod 600 ~/.ssh/config

      - name: Execute Remote Command
        run: |
          if [ ! -z "${{ vars.BRIDGE_HOST }}" ]; then
            ssh bridge 'ssh ${{ vars.TARGET_HOST }} "cd ${{ vars.APP_DIRECTORY }} && make upgrade_seadoc"'
          else
            ssh target "cd ${{ vars.APP_DIRECTORY }} && make upgrade_seadoc"
          fi